# Generated by Django 5.1.1 on 2026-03-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='gst',
            field=models.FloatField(default=0),
        ),
    ]
